name: Your Workflow

on:
  push:
    branches:
      - main

jobs:
  your-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Working Directory, Clean npm Cache, and Run npm Commands
        run: |
          cd /home/runner/work/xdfb/xdfb/
          npm cache clean --force
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: your-job
    environment:
      name: 'Production'
      url: ${{ needs.your-job.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip -d $GITHUB_WORKSPACE

      # Continue with the rest of your deployment steps
